spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/shopping?characterEncoding=UTF-8
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
mybatis:
  mapper-locations: classpath:mybatis/mapper/**/**.xml